/* Static verification: i18n key coverage + local asset paths + sitemap,
   product-page and image-file consistency. Run: node verify-site.js */
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = path.resolve(__dirname, "..");

/* ---- load site config + product data ---- */
let SITE_CONFIG = {};
try {
  const src = fs.readFileSync(path.join(ROOT, "site-config.js"), "utf8");
  const ctx = { window: {} };
  vm.createContext(ctx);
  vm.runInContext(src, ctx);
  SITE_CONFIG = ctx.window.SITE_CONFIG || {};
} catch (e) { /* keep {} */ }
const SITE_URL = String(SITE_CONFIG.siteUrl || "https://willis-perfume.com").replace(/\/+$/, "");

let data = [];
try {
  data = JSON.parse(fs.readFileSync(path.join(ROOT, "website_data_willis_perfume_FINAL_WITH_PRICES.json"), "utf8"));
} catch (e) { console.log("data load error:", e.message); }
const visible = data.filter(p => p.visible !== false);
const byId = new Map(data.map(p => [p.id, p]));

/* ---- load i18n dicts via vm (they use document/localStorage guards) ---- */
const i18nSrc = fs.readFileSync(path.join(ROOT, "i18n.js"), "utf8");
const ctxD = { document: {}, localStorage: { getItem: () => null } };
vm.createContext(ctxD);
try { vm.runInContext(i18nSrc, ctxD); } catch (e) { console.log("i18n load warn:", e.message); }
const EN = vm.runInContext("I18N.en", ctxD);
const AR = vm.runInContext("I18N.ar", ctxD);

let failures = 0;
function check(name, cond, detail = "") {
  if (cond) console.log(`  ok ${name}`);
  else { failures++; console.log(`  FAIL ${name} ${detail}`); }
}

/* ---- 1. data-i18n coverage: index.html + root list pages + products ---- */
const rootLists = ["collection.html", "featured.html", "contact.html"].filter(f => fs.existsSync(path.join(ROOT, f)));
const htmlFiles = [
  path.join(ROOT, "index.html"),
  ...rootLists.map(f => path.join(ROOT, f)),
  ...fs.readdirSync(path.join(ROOT, "products")).filter(f => f.endsWith(".html")).map(f => path.join(ROOT, "products", f))
];
const usedKeys = new Set();
for (const file of htmlFiles) {
  const html = fs.readFileSync(file, "utf8");
  for (const m of html.matchAll(/data-i18n(?:-placeholder|-aria)?="([^"]+)"/g)) usedKeys.add(m[1]);
}
const missingEn = [...usedKeys].filter(k => !(k in EN));
const missingAr = [...usedKeys].filter(k => !(k in AR));
check(`${usedKeys.size} data-i18n keys all present in EN`, missingEn.length === 0, missingEn.join(","));
check(`${usedKeys.size} data-i18n keys all present in AR`, missingAr.length === 0, missingAr.join(","));

/* ---- 2. t()/pt() keys used in app.js ---- */
const appSrc = fs.readFileSync(path.join(ROOT, "app.js"), "utf8");
const appKeys = new Set();
for (const m of appSrc.matchAll(/(?<![A-Za-z0-9_$])(?:t|pt)\("([^"]+)"/g)) appKeys.add(m[1]);
const missingApp = [...appKeys].filter(k => !(k in EN) && k !== "__keep__");
check(`${appKeys.size} t()/pt() keys used in app.js all present`, missingApp.length === 0, missingApp.join(","));

/* ---- 3. local asset references resolve ---- */
function localRefs(html, dir) {
  const refs = [];
  for (const m of html.matchAll(/(?:src|href)="([^"]+)"/g)) {
    let r = m[1];
    if (/^(https?:|mailto:|tel:|#|data:)/i.test(r)) continue;
    if (r.startsWith("javascript:")) continue;
    if (r.includes("fbq('init'")) continue;
    r = r.split("?")[0].split("#")[0];
    if (!r) continue;
    refs.push({ raw: m[1], resolved: path.resolve(dir, r) });
  }
  return refs;
}
let totalRefs = 0, badRefs = 0;
for (const file of htmlFiles) {
  const html = fs.readFileSync(file, "utf8");
  const dir = path.dirname(file);
  for (const { raw, resolved } of localRefs(html, dir)) {
    totalRefs++;
    if (!fs.existsSync(resolved)) {
      badRefs++;
      console.log(`  MISSING ${path.relative(ROOT, file)} -> ${raw}`);
    }
  }
}
check(`all ${totalRefs} local asset refs resolve (${htmlFiles.length} pages)`, badRefs === 0, `${badRefs} broken`);

/* ---- 4. sitemap.xml consistency (auto-generated by generate-pages.js) ---- */
const sitemapPath = path.join(ROOT, "sitemap.xml");
const sitemap = fs.existsSync(sitemapPath) ? fs.readFileSync(sitemapPath, "utf8") : "";
const sitemapUrls = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m => m[1]);

check("sitemap.xml exists", fs.existsSync(sitemapPath));
const requiredRoot = [`${SITE_URL}/`, `${SITE_URL}/collection.html`, `${SITE_URL}/featured.html`, `${SITE_URL}/contact.html`];
check("sitemap has all root pages",
  requiredRoot.every(u => sitemapUrls.includes(u)),
  requiredRoot.filter(u => !sitemapUrls.includes(u)).join(","));
const missingProductUrls = visible
  .map(p => `${SITE_URL}/products/${p.id}.html`)
  .filter(u => !sitemapUrls.includes(u));
check(`sitemap covers all ${visible.length} visible products`, missingProductUrls.length === 0, missingProductUrls.join(","));
const dupes = sitemapUrls.filter((u, i) => sitemapUrls.indexOf(u) !== i);
check("sitemap has no duplicate URLs", dupes.length === 0, dupes.join(","));

/* ---- 5. product pages vs data ---- */
const missingPages = visible.filter(p => !fs.existsSync(path.join(ROOT, "products", `${p.id}.html`)));
check(`product pages exist for all ${visible.length} visible products`, missingPages.length === 0, missingPages.map(p => p.id).join(","));
const stalePages = fs.readdirSync(path.join(ROOT, "products"))
  .filter(f => f.endsWith(".html"))
  .map(f => f.replace(/\.html$/, ""))
  .filter(id => !byId.has(id));
check("no stale product pages (not in data)", stalePages.length === 0, stalePages.join(","));

/* ---- 6. product image references + orphan image files ---- */
const missingImages = data.flatMap(p => {
  const refs = [p.image, ...(p.image_gallery || [])].filter(Boolean);
  return refs.filter(r => !fs.existsSync(path.join(ROOT, r))).map(r => `${p.id} -> ${r}`);
});
check(`all product images exist (${data.length} products)`, missingImages.length === 0, missingImages.join(", "));

const imageDir = path.join(ROOT, "images");
const specialNames = new Set(["bottle", "logo", "og-image", "apple-touch-icon", "favicon-32x32", "leaf-gold-1", "leaf-gold-2", "leaf-gold-3"]);
const orphanImgs = fs.existsSync(imageDir)
  ? fs.readdirSync(imageDir)
      .filter(f => /\.(webp|png|jpg|jpeg)$/i.test(f))
      .map(f => f.replace(/\.[^.]+$/, "").toLowerCase())
      .filter(base => !byId.has(base) && !specialNames.has(base))
  : [];
check("no orphan images without a matching product", orphanImgs.length === 0, orphanImgs.join(", "));

console.log(failures === 0 ? "\nVERIFY OK" : `\n${failures} PROBLEM(S)`);
process.exit(failures === 0 ? 0 : 1);